name: thermiq2-we
version: 0.0.1
slug: thermiq2w
description: ThermIQ2-web container based on Apache and PHP8
url: https://github.com/ThermIQ/hassio-addons/tree/master/thermiq2_web
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
webui: http://[HOST]:[PORT:81]
map:
  - ssl:rw
  - media:rw
  - share:rw
ingress: true
init: false
panel_icon: mdi:web-box
options:
  website_name: ThermIQ
  thermiq_user: 
  thermiq_licenskey:
  mariadb_user:
  mariadb_pw:
  thermiq_init: true
  document_root: /share/htdocs
  php_ini: /share/php.ini
  default_conf: default
  default_ssl_conf: default

  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem
  init_commands: []
schema:
  website_name: str
  thermiq_user:  str
  thermiq_licenskey: str
  mariadb_user: str
  mariadb_pw : str
  thermiq_init: bool
  document_root: str
  php_ini: str
  default_conf: str
  default_ssl_conf: str

  username: str?
  password: password?
  ssl: bool
  certfile: str
  keyfile: str
  init_commands:
    - str?
ports:
  80/tcp: 81
  443/tcp: 8324
ports_description:
  80/tcp: Web interface http
  443/tcp: SSL Web interface
