name: thermiq_listener
version: 0.0.1
slug: thermiq2
description: ThermIQ MQTT Listener to MariaDB
url: https://github.com/ThermIQ/hassio-addons/tree/master/thermiq_listener
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
boot: auto
webui: 
map:
  - ssl:rw
  - media:rw
  - share:rw
ingress: false
init: false
panel_icon: mdi:web-box
options:

  mqtt_server:
  mqtt_port:
  mqtt_user: 
  mqtt_pw:
  mariadb_user:
  mariadb_pw:
  php_ini: str



  ssl: false
  certfile: fullchain.pem
  keyfile: privkey.pem

schema:
  mqtt_server: str
  mqtt_port: str
  mqtt_user: str
  mqtt_pw: str
  mariadb_user: str
  mariadb_pw: str
  mariadb_user: str
  mariadb_pw : str
  php_ini: str

  ssl: bool
  certfile: str
  keyfile: str

ports:

ports_description:

